language: go
go:
  - 1.5.x
  - 1.6.x
  - 1.7.x

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libpam-dev
  - go get github.com/msteinert/pam 

install:
  - go get -t -v ./...

script: 
  - go build -v -tags "pam"
  - go test -v -cover -race ./...
