version: "{build}"
skip_tags: true
clone_folder: c:\gogs.io\gogs
clone_depth: 1

environment:
  GO111MODULE: on
  GOPROXY: "https://proxy.golang.org,direct"
  GOVERSION: 1.13.3

build: false
deploy: false

install:
  - go env
  - go build -v
