version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.x
  build:
    commands:
      - echo Build started on `date`
      - CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-extldflags "-static"' -o gogs
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - gogs
  name: gogs
