version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - zip -r gogs-${CODEBUILD_BUILD_NUMBER}.zip . -x "*.git*" "*.zip" 
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - gogs-*.zip
  name: gogs-${CODEBUILD_BUILD_NUMBER}.zip
