version: 0.2

env:
  variables:
    HASH_COMMIT: ${CODEBUILD_RESOLVED_SOURCE_VERSION}

phases:
  install:
    runtime-versions:
      golang: 1.x
  build:
    commands:
      - echo Build started on `date`
      - go build -o gogs
  post_build:
    commands:
      - echo Build completed on `date`
      - mv gogs gogs-${HASH_COMMIT:0:7}

artifacts:
  files:
    - gogs-${HASH_COMMIT:0:7}
  name: gogs-${HASH_COMMIT:0:7}
