version: 0.2

env:
  variables:
    GOPATH: /go

phases:
  install:
    runtime-versions:
      golang: 1.21
    commands:
      - echo Installing dependencies...
      - go get -v -t -d ./...

  build:
    commands:
      - echo Build started on `date`
      - go build -v -o gogs-binary

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - gogs-binary
  name: gogs-binary-$(date +%Y-%m-%d)
