version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.21
  build:
    commands:
      - echo Build started on `date`
      - go build -o gogs
  post_build:
    commands:
      - echo Build completed on `date`
      - HASH_COMMIT=$(git rev-parse --short HEAD)
      - mv gogs gogs-$HASH_COMMIT

artifacts:
  files:
    - gogs-$HASH_COMMIT
  name: gogs-$HASH_COMMIT
