version: 0.2

env:
  variables:
    GOPATH: /go
    COMMIT_HASH: "${CODEBUILD_RESOLVED_SOURCE_VERSION}"
    BINARY_NAME: "gogs-binary-${CODEBUILD_RESOLVED_SOURCE_VERSION:0:7}"

phases:
  install:
    runtime-versions:
      golang: 1.21
    commands:
      - echo Installing dependencies...
      - go get -v -t -d ./...

  build:
    commands:
      - echo Build started on `date`
      - echo Commit Hash: $COMMIT_HASH
      - go build -v -o $BINARY_NAME

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - $BINARY_NAME
  discard-paths: yes
