version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - zip -r gogs.zip . -x "*.git*" "*.zip" 
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - gogs.zip
  name: gogs.zip
