version: 0.2
phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y docker.io git
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO
      - export GITHUB_TOKEN=$(aws secretsmanager get-secret-value --secret-id github-token --query SecretString --output text)
  build:
    commands:
      - echo Building the Docker image...
      - export COMMIT_HASH=$(git rev-parse --short HEAD)
      - docker build -t gogs:$COMMIT_HASH .
      - docker tag gogs:$COMMIT_HASH $ECR_REPO:$COMMIT_HASH
      - docker push $ECR_REPO:$COMMIT_HASH
  post_build:
    commands:
      - echo Updating Kubernetes deployment file...
      - git clone https://github.com/fenrikk/gogs-kuber-deployment.git
      - cd gogs-kuber-deployment
      - |
        sed -i "s|image: .*|image: $ECR_REPO:$COMMIT_HASH|" gogs-deployment-service.yaml
      - git config --global user.email "codebuild@example.com"
      - git config --global user.name "CodeBuild"
      - git add gogs-deployment-service.yaml
      - git commit -m "Update image to $COMMIT_HASH"
      - git push https://oauth2:$GITHUB_TOKEN@github.com/fenrikk/gogs-kuber-deployment.git
