sonar.projectKey=gogs
sonar.sources=.
sonar.go.coverage.reportPaths=coverage.out
sonar.coverage.exclusions=**/*_test.go
sonar.test.exclusions=**/*_test.go
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.tests.reportPaths=test-report.out

sonar.coverage.minimum=40
